#!/bin/bash
#
# Copyright 2020 Northern.tech AS
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

set -e

IMAGE_NAME_PREFIX=mendersoftware/mender-dist-packages:builder

declare -A debian_buster=(
  [distro]="debian"
  [version]="buster"
)
declare -A debian_bullseye=(
  [distro]="debian"
  [version]="bullseye"
)
declare -A ubuntu_bionic=(
  [distro]="ubuntu"
  [version]="bionic"
)
declare -A ubuntu_focal=(
  [distro]="ubuntu"
  [version]="focal"
)
declare -a BASE_IMAGES=(
    debian_buster
    debian_bullseye
    ubuntu_bionic
    ubuntu_focal
)
