#!/bin/sh

set -e

ACTION="$1"
OLD_VERSION="$2"
NEW_VERSION="$3"

case "$ACTION" in
    install)
        # mender-update is going to replace files that are owned by the old
        # mender-client. mender-client is also going to be installed, which will remove
        # those files and solve those conflicts, but not until later. Therefore we need to
        # divert these files now, and restore them after the new mender-client package is
        # also installed.
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-bootloader-integration
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-hostinfo
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-network
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-os
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-provides
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-rootfs-type
        dpkg-divert --add --no-rename /etc/mender/inventory/mender-inventory-update-modules
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/deb
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/directory
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/docker
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/rootfs-image
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/rpm
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/script
        dpkg-divert --add --no-rename /usr/share/mender/modules/v3/single-file
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-bootloader-integration
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-hostinfo
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-network
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-os
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-provides
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-rootfs-type
        dpkg-divert --add --no-rename /usr/share/mender/inventory/mender-inventory-update-modules
        dpkg-divert --add --no-rename /etc/mender/scripts/version
        ;;

    *)
        # Nothing to do for upgrades.
        ;;
esac

exit 0
